### ISSUE TITLE
List VPCs

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#1]
It would be good to list all VPCs, that is ones defined within a region as well as ones peered directly as well as through a transit gateway attachment.

**Comment by leandrodamascena** [comment]
Nice @meshuga. I'll implement this feature in next releases.. you can inform only region (or get through aws credentials) and show all vpcs, peering and attachments.. maybe in one or two week.

Let me know if actual features are running ok..

**Comment by leandrodamascena** [comment]
Now script check all vpcs in the same region!
