### ISSUE TITLE
Check for VPCE in policies

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#13]
It's possible to refer VPC Endpoint [1] instead of VPC id when defining policies. It even seems like is the only option in case of SQS Policies [2].

The tool should correlate endpoints to VPCs when generating a report.

Refs
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourcevpce
[2] https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-api-permissions-reference.html

**Comment by leandrodamascena** [comment]
Good point. I use VPCE here to access services through a private subnet.

I'll check this.

**Comment by leandrodamascena** [comment]
1 - VPCE endpoint
![image](https://user-images.githubusercontent.com/4295173/81353783-ec8d6a00-90c1-11ea-8a6e-9f32bb6a0ec0.png)

2 - SQS Policy Document
![image](https://user-images.githubusercontent.com/4295173/81353800-f616d200-90c1-11ea-94d5-72533b0702e5.png)

3 - Script output
![image](https://user-images.githubusercontent.com/4295173/81353890-2bbbbb00-90c2-11ea-8503-50e4cbe02d3d.png)

**Comment by meshuga** [comment]
Looks nice! I'll try to provide more information in the report in a PR

**Comment by leandrodamascena** [comment]
Included in 0.5.0 release.
