### ISSUE TITLE
Add graph visualization export

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#16]
Since we often have situations when network can get complex, it's often simpler to represent the network as a graph. A ready tool can be used for that purpose, which is [cloudmapper](https://github.com/duo-labs/cloudmapper).

**Comment by leandrodamascena** [comment]
Ok, i've already used cloudmapper only for tests proposes... You know about diagrams [1]? Maybe a good way too draw diagrams and show connections between VPC and resources...

Will analyze both solutions.. 

Refs
[1] https://github.com/mingrammer/diagrams

**Comment by meshuga** [comment]
Thais a foot project as well! Definitely better to visualization tool but doesn’t much look to babe a autogeneration mechanisms in place. Good for us :)

**Comment by leandrodamascena** [comment]
Yeah, a really nice project.. I use this to draw archs before to implement... Infra as a code is a really good solution...

Thinking about implementation we can do in 2 ways:

1 - Simple and first release - show a vpc and all resources inside

![image](https://user-images.githubusercontent.com/4295173/81502333-38fcc380-92d5-11ea-857d-790c02325f57.png)

2 - Include subnets and put resources inside of those..

![image](https://user-images.githubusercontent.com/4295173/81502446-ed96e500-92d5-11ea-8231-2f9a2e84b824.png)

**Comment by meshuga** [comment]
It's hard to tell. I usually make distinctions between public/private subnets but not between concrete instantiations. None of the is perfect for me and I think everyone can agree with me (not a selfish opinion). It's just one of common scenarios - https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html

For reference, the issue is related with https://github.com/mingrammer/diagrams/issues/1 and https://github.com/mingrammer/diagrams/issues/6.

**Comment by leandrodamascena** [comment]
There are lot of things to improve, but check this prototype if make sense... Now all executions must have return a list with resource-id and tool use to print diagram... Working with lambda and igw for tests... Add a parameter "-d test"

I combined all resource-id of a certain parent resource (compute, analytics, database...) in a cluster to improve user experience. ]

![image](https://user-images.githubusercontent.com/4295173/81513898-bc450600-9323-11ea-96db-83e77341a91a.png)

![image](https://user-images.githubusercontent.com/4295173/81513903-c23ae700-9323-11ea-9f57-f160df8d7eef.png)

**Comment by leandrodamascena** [comment]
I think it's a good new implementation!! :D

We maybe discuss about connections inside diagram, but it's detail.

![image](https://user-images.githubusercontent.com/4295173/82766839-4740f880-9e1a-11ea-8fbf-b9b39223001f.png)
