### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by leandrodamascena** [leandrodamascena/aws-network-discovery#21]
Refactor code to implement new enhancements and fix problems:

1 - PEP compliance
2 - New and fast way to instance classes to run checks
3 - General method to parse and analyze most of checks

**Comment by meshuga** [comment]
It would be good to have common way of error handling. If a single resource analysis/generation fails, the whole process of network discovery should not be aborted.

I think it would be also good for the code to be split into three parts:
1. Resource generation
2. Report printing
3. Other data exports e.g. #16 

We could create a new class e.g. Resource, which would store details like type, id, name, perhaps relations to other resources

**Comment by leandrodamascena** [comment]
Hmmm ok.. Let me know more about your idea of a Resource class.... 

Other itens I agree totally.. We maybe focus now on finish all resources that use VPC, and in each release refactor a piece of code...

**Comment by meshuga** [comment]
Maybe something like below would be working for us:
```python
class Resource(NamedTuple):
    id: str # we could stick with Terraform id approach for identification of resources to ensure uniqueness within same type
    name: str
    type: str # we could stick to Terraform names e.g. aws_nat_gateway
    details: str # to keep e.g. path that leads to a VPC, later we could add more graph-like fields to define eges

class NATGATEWAY: # or any other resource detection class
    def run(self) -> List[Resource]:
        resources = []
        ... # add resources there
        return resources

class ReportGenerator:
    def process(self, resources):
        ... group resources by type and print them

class DiagramGenerator:
    def process(self, resources):
        ... draw diagram 
```

**Comment by leandrodamascena** [comment]
Ok @meshuga. Get it!.. I'll create a separate branch to implement a prototype and validate the idea... 

It really is a simpler way to store and reuse all discovered resources in report / diagram / export classes.

**Comment by meshuga** [comment]
Agree, that's more or less how Terraformer works :)

**Comment by leandrodamascena** [comment]
Code refactor to implement a new kind of check. Now is much cleaner and allows to process new kind of reports, outputs, diagrams, whatever.

78cb09e

**Comment by leandrodamascena** [comment]
- [x] Resource generation
- [x] Report printing
- [ ] Other data exports e.g. #16
- [x] PEP-8 rules
- [x] New and fast way to instance classes to run checks
- [x] General method to parse and analyze most of checks
