### ISSUE TITLE
Enhance Route Tables reporting

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#24]
Currently a route table is reported to be directly associated with a VPC but in practice, the relationship is much more complex, with the tables being associated with subnets. The tool should detect that relationship and report it properly.
There is also a concept of a default table, that should be reported.

**Comment by patrykorwat** [comment]
The initial idea can be enhanced to detect route table associations to subnets to:
1. Be able to create a subnets groups: private and public
2. Trick diagrams library to aggregate multiple edges that that to all subnets within a cluster to have one connection to such private/public cluster

The outcome will be simpler diagrams. For the change, the `fdp` graphviz engine must be used.

**Comment by patrykorwat** [comment]
Blocked by https://github.com/mingrammer/diagrams/issues/17.

For the time being, we can aggregate the multiple subnets into one (perhaps represented with a bigger icon), in order to make the diagram cleaner.
