### ISSUE TITLE
Add new network detection mode: IoT

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#29]
Right now the tool detects resources within VPC but that's not everything that rund within AWS.
Another area that can need an ability to detect network is IoT.

Because VPC resources and IoT resources can be drawn as independent entities (with small overlap), there should be a separate command to detect either of those two.

For VPC detection the following command can be issued:
```
$ ./aws-network-discovery.py vpc --vpc-id vpc-xxxxxxx --region-name xx-xxxx-xxx
```

For IoT detection the following command can be issued:
```
$ ./aws-network-discovery.py iot --vpc-id vpc-xxxxxxx --region-name xx-xxxx-xxx
```

There could be overlaps e.g. an IoT Rule can call a Lambda Function but that is acceptable to have.

**Comment by leandrodamascena** [comment]
Now this tool can check IoT things and connections... Some problems related to diagrams...

![image](https://user-images.githubusercontent.com/4295173/83702306-38b9c480-a604-11ea-851a-2fd137767d18.png)

**Comment by patrykorwat** [comment]
LGTM
