### ISSUE TITLE
Add new network detection mode: Policy

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#31]
Since the tool is able to detect VPC resources, there's a task to detect IoT resources, it would be possible to detect policy resources.

We can all agree IAM policies are complex, with a lot of moving parts and manual verification of evaluation logic is not easy. The tool can help to get an overview of policies within an account.

Similarly to #29, there can be a command to initiate policy reporting:
```
$ ./aws-network-discovery.py policy --vpc-id vpc-xxxxxxx --region-name xx-xxxx-xxx

```

**Comment by leandrodamascena** [comment]
You mean that this tool could analyze all policies and discover which resources those policies allow access or specific policies that are referring to some network item like vpc, vpce.

Let me know further information about this idea.
