### ISSUE TITLE
More compute resources

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#6]
It would be good to list:
- [x] ECS Fargate clusters
- [x] EKS clusters
- [x] EMR clusters
- [x] MSK clusters
- [x] SQS Policies (like in #2)
- [x] ASGs (through subnets)

**Comment by leandrodamascena** [comment]
Added SQS Queue Policies. In this case boto3 return a non default response like other resources.. maybe it's a legacy version..

**Comment by leandrodamascena** [comment]
> It would be good to list:
> 
> * [ ]  ASGs (through subnets)

ASGs launches EC2 instances every time that scale-out process occurs and if in "ASG Groups" a custom vpc was selected than existent check (EC2 INSTANCES) will catch that instances and alert... 

I know that there may be some situations where the desired capacity is zero and there may not be instances launched by ASG, but the "ASG Group" will contain the custom vpc and it would be interesting to inform. But maybe there is duplicate information, what do you think?

**Comment by leandrodamascena** [comment]
> It would be good to list:
> 
> * [x]  MSK clusters

Added MSK cluster..
Lot of checks are using subnet query from vpc... in next releases I'll refactor this piece of code..

**Comment by meshuga** [comment]
I think it's desirable to list the ASGs, even those with `0` desired capacity.

Right now I got a list of EC2 instances but majority of them are created as a part of an ASG. It would be good to have a reference to that somewhere as well.

**Comment by leandrodamascena** [comment]
Added EC2 check..

**Comment by leandrodamascena** [comment]
Added ASG check.

**Comment by leandrodamascena** [comment]
Everything done... Closing issue.
