### ISSUE TITLE
More database resources

### ISSUE THREAD

**Issue by meshuga** [leandrodamascena/aws-network-discovery#8]
It would be good to have:
- [x] Elasticsearch
- [x] DocumentDB

**Comment by leandrodamascena** [comment]
Elasticsearch has policies access too, so this update checks either a domain using vpc or a policy access.

**Comment by leandrodamascena** [comment]
Searching directly in instances of DocumentDB is more reasonable than find cluster and after find instances of that cluster..

**Comment by meshuga** [comment]
Good catch with that ES policy.

**Comment by meshuga** [comment]
@leandrodamascena DocumentDB detects RDS instances on my account :)

**Comment by leandrodamascena** [comment]
You sure @meshuga. Even boto3 client instanced different resources (rds/docdb), they use the same method behind to get db_instances, the only thing that diff between is engine... I added engine filter in both class: RDS and DOCUMENTDB

**Comment by meshuga** [comment]
Thanks!
